<?php

/**
 * @file
 * Contains bvisa_res_opts_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bvisa_res_opts_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bvisa_res_opts_migration module.
    case 'help.page.bvisa_res_opts_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The migration for the BVisa Response Options') . '</p>';
      return $output;

    default:
  }
}
