<?php

/**
 * @file
 * Contains bvisa_blackbox_education.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bvisa_blackbox_education_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bvisa_blackbox_education module.
    case 'help.page.bvisa_blackbox_education':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Black Box Model for the B Visa Class which installs the Education DB') . '</p>';
      return $output;

    default:
  }
}
