<?php

/**
 * @file
 * Contains bvisa_question_map.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bvisa_question_map_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bvisa_question_map module.
    case 'help.page.bvisa_question_map':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The map for the BVisa Questions') . '</p>';
      return $output;

    default:
  }
}
