<?php

/**
 * @file
 * Contains ovr_webform_options.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ovr_webform_options_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ovr_webform_options module.
    case 'help.page.ovr_webform_options':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('All of the helpful Webform Options used for Ovr') . '</p>';
      return $output;

    default:
  }
}
